# -*- mode: python ; coding: utf-8 -*-

from PyInstaller.utils.hooks import collect_data_files
google_datas = collect_data_files('googleapiclient')
certifi_datas = collect_data_files('certifi')

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('assets', 'assets'), ('backup_tool', 'backup_tool')] + google_datas + certifi_datas,
    hiddenimports=[
        'schedule',
        'requests',
        'urllib3',
        'watchdog',
        'watchdog.observers',
        'watchdog.events',
        'google_auth_httplib2',
        'httplib2',
        'googleapiclient',
        'googleapiclient.discovery',
        'googleapiclient.errors',
        'googleapiclient.http',
        'google.oauth2',
        'google.oauth2.service_account',
        'win32api',
        'win32event',
        'win32con',
        'win32gui',
        'win32file',
        'win32process',
        'win32com',
        'win32com.client',
        'pywintypes',
        'pythoncom',
        'schedule',
        'unicodedata',
        'idna',
        'idna.core',
        'idna.codec',
        'charset_normalizer',
        'certifi',
        'urllib3.util',
        'urllib3.util.url',
        'http.cookies',
        'http.cookiejar',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ATLED_BK',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=True,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['assets\\app_icon.ico'],
)
